version: "3"

services:
  finder:
    build: .
    restart: "no"
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    container_name: mc_server_finder

  postgres:
    image: postgres:11-alpine
    restart: "always"
    env_file:
      - .env
    volumes:
      - db_volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: mc_server_finder_db

volumes:
  db_volume:
    external: true
